2024-02-29 16:21:31: INFO - Programa Codefix iniciado com sucesso
2024-02-29 16:22:01: WARNING - Repositório teste_sonarqube_01 já criado!
2024-02-29 16:22:01: INFO - Baixando as últimas atualizações do repositório teste_sonarqube_01
2024-02-29 16:22:09: INFO - Repositório teste_sonarqube_01 atualizado com sucesso
2024-02-29 16:22:09: INFO - Arquivo sonar-project.properties já existe.
2024-02-29 16:22:09: INFO - Compactando C:\Users\NZ366ES\OneDrive - EY\Documents\Assets\codefix\teste_sonarqube_01 no arquivo teste_sonarqube_01.zip
2024-02-29 16:22:10: INFO - Arquivo zip criado com sucesso
2024-02-29 16:23:25: INFO - Sonar Scanner executado com sucesso
2024-02-29 16:30:46: ERROR - Não foi possível analisar o log do Sonarqube
Traceback (most recent call last):
  File "C:\Users\NZ366ES\AppData\Local\Temp\ipykernel_22840\1622027135.py", line 12, in carregar_base_projeto_v2
    df_issues.sort_values('column_name', inplace=True)
  File "C:\Users\NZ366ES\Anaconda3\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\NZ366ES\Anaconda3\lib\site-packages\pandas\core\frame.py", line 6313, in sort_values
    k = self._get_label_or_level_values(by, axis=axis)
  File "C:\Users\NZ366ES\Anaconda3\lib\site-packages\pandas\core\generic.py", line 1840, in _get_label_or_level_values
    raise KeyError(key)
KeyError: 'column_name'
2024-02-29 16:47:02: INFO - Resultados do scanner do repositório teste_sonarqube_01
2024-02-29 16:47:02: INFO - Codigo: codigo_errado.py	Linha: 4	Issue: Rename function "addBug" to match the regular expression ^[a-z_][a-z0-9_]*$.
2024-02-29 16:47:02: INFO - Codigo: codigo_errado.py	Linha: 10	Issue: Rename function "showVulnerability" to match the regular expression ^[a-z_][a-z0-9_]*$.
2024-02-29 16:47:02: INFO - Codigo: codigo_java.java	Linha: 2	Issue: Rename this method name to match the regular expression '^[a-z][a-zA-Z0-9]*$'.
2024-02-29 16:47:02: INFO - Codigo: codigo_java.java	Linha: 6	Issue: Rename this method name to match the regular expression '^[a-z][a-zA-Z0-9]*$'.
2024-02-29 16:47:02: INFO - Codigo: codigo_java.java	Linha: 7	Issue: Replace this use of System.out or System.err by a logger.
2024-02-29 16:47:02: INFO - Codigo: codigo_java.java	Linha: 12	Issue: Make sure "divisor" can't be zero before doing this division.
2024-02-29 16:47:02: INFO - Codigo: codigo_java.java	Linha: 15	Issue: Rename this method name to match the regular expression '^[a-z][a-zA-Z0-9]*$'.
2024-02-29 16:47:02: INFO - Codigo: codigo_java.java	Linha: 17	Issue: Remove this useless assignment to local variable "val1".
2024-02-29 16:47:02: INFO - Codigo: codigo_java.java	Linha: 18	Issue: Remove this useless assignment to local variable "val2".
2024-02-29 16:47:02: INFO - Codigo: codigo_java.java	Linha: 21	Issue: Rename this local variable to match the regular expression '^[a-z][a-zA-Z0-9]*$'.
2024-02-29 16:47:02: INFO - Codigo: codigo_java.java	Linha: 22	Issue: Rename this local variable to match the regular expression '^[a-z][a-zA-Z0-9]*$'.
2024-02-29 16:47:02: INFO - Codigo: codigo_simples_bug.py	Linha: 1	Issue: Remove the unused function parameter "b".
2024-02-29 16:47:02: INFO - Codigo: interface.py	Linha: 88	Issue: Remove this commented out code.
2024-02-29 16:47:02: INFO - Codigo: interface.py	Linha: 102	Issue: Remove this commented out code.
2024-02-29 16:47:02: INFO - Codigo: leitor_cnh_versao2.py	Linha: 55	Issue: Remove this commented out code.
2024-02-29 16:47:02: INFO - Codigo: leitor_cnh_versao2.py	Linha: 203	Issue: Remove this commented out code.
2024-02-29 16:47:02: INFO - Codigo: python_bugado.py	Linha: 11	Issue: Remove the unused local variable "wrong_name".
2024-02-29 16:47:02: INFO - Codigo: python_bugado.py	Linha: 20	Issue: Merge this if statement with the enclosing one.
2024-02-29 16:47:02: INFO - Codigo: teste_erros.py	Linha: 35	Issue: Rename this local variable "largeList" to match the regular expression ^[_a-z][a-z0-9_]*$.
2024-02-29 16:48:45: INFO - Código dos arquivos extraidos com sucesso
2024-02-29 16:49:04: INFO - error_code=429 error_message='Requests to the Chatcompletions_Create Operation under Azure OpenAI API version 2023-03-15-preview have exceeded call rate limit of your current OpenAI S0 pricing tier. Please retry after 2 seconds. Please go here: https://aka.ms/oai/quotaincrease if you would like to further increase the default rate limit.' error_param=None error_type=None message='OpenAI API error received' stream_error=False
2024-02-29 16:49:04: INFO - error_code=429 error_message='Requests to the Chatcompletions_Create Operation under Azure OpenAI API version 2023-03-15-preview have exceeded call rate limit of your current OpenAI S0 pricing tier. Please retry after 2 seconds. Please go here: https://aka.ms/oai/quotaincrease if you would like to further increase the default rate limit.' error_param=None error_type=None message='OpenAI API error received' stream_error=False
2024-02-29 16:59:11: INFO - Arquivo codigo_errado.py escrito com sucesso
2024-02-29 16:59:11: INFO - Arquivo codigo_java.java escrito com sucesso
2024-02-29 16:59:11: INFO - Arquivo codigo_simples_bug.py escrito com sucesso
2024-02-29 16:59:11: INFO - Arquivo interface.py escrito com sucesso
2024-02-29 16:59:11: INFO - Arquivo leitor_cnh_versao2.py escrito com sucesso
2024-02-29 16:59:11: INFO - Arquivo python_bugado.py escrito com sucesso
2024-02-29 16:59:11: INFO - Arquivo teste_erros.py escrito com sucesso
